<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNu6sl4x\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNu6sl4x/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNu6sl4x.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNu6sl4x\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNu6sl4x\appProdProjectContainer([
    'container.build_hash' => 'Nu6sl4x',
    'container.build_id' => '2b4b1a77',
    'container.build_time' => 1559058768,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNu6sl4x');
