<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPwseuzw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPwseuzw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPwseuzw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPwseuzw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPwseuzw\appDevDebugProjectContainer([
    'container.build_hash' => 'Pwseuzw',
    'container.build_id' => 'd77c7807',
    'container.build_time' => 1560734016,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPwseuzw');
