<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJe7nfsh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJe7nfsh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJe7nfsh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJe7nfsh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJe7nfsh\appDevDebugProjectContainer([
    'container.build_hash' => 'Je7nfsh',
    'container.build_id' => '76695a62',
    'container.build_time' => 1559833953,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJe7nfsh');
